name: Action Practice On Issues
on: issues
jobs:
    issue:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github context
              run: echo "${{ toJson(github.event.issue)}}"